In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("overlapping_schwarz_results.csv")
df

,n,N,NN,overlap_n,preconditioner,solver,coefficient,coefficient_param,residual norm,iterations,condition number
0,256,16,16,0,Additive,CG,constant,NaN,3.046598e-06,143,289.141499
1,256,16,16,0,Multiplicative Symmetric,CG,constant,NaN,3.327340e-06,69,66.326319
2,256,16,16,0,Multiplicative,GMRES,constant,NaN,7.263641e-07,92,NaN
3,256,16,16,0,Hybrid,CG,constant,NaN,3.041298e-06,83,98.113551
4,256,16,16,1,Additive,CG,constant,NaN,3.491619e-06,125,295.116423
...,...,...,...,...,...,...,...,...,...,...,...
415,256,256,256,0,Hybrid,CG,coarse checkerboard,1000000.0,1.766078e-06,17,3.041883
416,256,256,256,0,Additive,CG,solvers checkerboard,1000000.0,3.025374e-06,36,16.326933
417,256,256,256,0,Multiplicative Symmetric,CG,solvers checkerboard,1000000.0,2.419997e-06,16,3.565873
418,256,256,256,0,Multiplicative,GMRES,solvers checkerboard,1000000.0,2.279364e-06,20,NaN
419,256,256,256,0,Hybrid,CG,solvers checkerboard,1000000.0,1.654653e-06,17,3.043554

In [13]:
def get_order(row):
    h = 1 / row["n"]
    H = 1 / row["N"]
    HH = 1 / row["NN"]
    delta = row["overlap_n"] / row["n"]
    return HH * HH / H / max(h, delta)

df["estimate"] = df.apply(get_order, axis=1)
df["ratio"] = df["condition number"] / df["estimate"]

In [14]:
df["solver"] = df["solver"] + "+" + df["preconditioner"]

In [32]:
df[(df.NN == 16) & (df.n == 256) & (df.coefficient == "constant")].pivot_table(values="iterations", index=["N", "overlap_n"], columns="solver", aggfunc="min")

solver         CG+Additive  CG+Hybrid  CG+Multiplicative Symmetric  \
N   overlap_n
16  0                  143         83                           69
    1                  125         82                           47
    2                  105         77                           38
    4                   80         63                           26
    8                   63         56                           16
32  0                  153         95                           73
    1                  141         90                           52
    2                  125         80                           40
    4                  106         75                           32
64  0                  173        125                           80
    1                  152         97                           56
    2                  155         90                           42
128 0                  213        171                           93
    1                  181        109                           59
256 0                  271        239                          112

solver         GMRES+Multiplicative
N   overlap_n
16  0                            92
    1                            58
    2                            56
    4                            42
    8                            31
32  0                            87
    1                            67
    2                            67
    4                            65
64  0                            87
    1                            88
    2                            86
128 0                           116
    1                           104
256 0                           251

In [31]:
df[(df.NN == 16) & (df.n == 256) & (df.coefficient == "coarse checkerboard")].pivot_table(values="iterations", index=["N", "overlap_n"], columns="solver", aggfunc="min")

solver         CG+Additive  CG+Hybrid  CG+Multiplicative Symmetric  \
N   overlap_n
16  0                   48         21                           25
    1                   80         50                           24
    2                   74         47                           20
    4                   63         46                           17
    8                   68         47                           15
32  0                  100         80                           50
    1                   95         62                           38
    2                   88         53                           35
    4                   87         59                           29
64  0                  131        119                           65
    1                  103         69                           40
    2                  103         65                           37
128 0                  177        169                           81
    1                  123         88                           42
256 0                  239        231                          105

solver         GMRES+Multiplicative
N   overlap_n
16  0                            41
    1                            29
    2                            28
    4                            26
    8                            24
32  0                            68
    1                            60
    2                            40
    4                            37
64  0                            88
    1                            53
    2                            51
128 0                           160
    1                            62
256 0                           340

In [28]:
df[(df.NN == 16) & (df.n == 256) & (df.coefficient == "solvers checkerboard")].pivot_table(values="iterations", index=["N", "overlap_n"], columns="solver", aggfunc="min")

solver         CG+Additive  CG+Hybrid  CG+Multiplicative Symmetric  \
N   overlap_n
16  0                   48         21                           26
    1                   80         51                           23
    2                   73         52                           21
    4                   60         43                           18
    8                   68         48                           14
32  0                   81         54                           38
    1                  103         62                           33
    2                   94         59                           28
    4                  111         65                           27
64  0                  134        107                           59
    1                  131         92                           40
    2                  155         97                           38
128 0                  231        191                           89
    1                  224        183                           52
256 0                  389        337                          143

solver         GMRES+Multiplicative
N   overlap_n
16  0                            36
    1                            31
    2                            29
    4                            27
    8                            25
32  0                            51
    1                            46
    2                            44
    4                            45
64  0                            72
    1                            65
    2                            67
128 0                           133
    1                            97
256 0                           340

In [18]:
# GMRES?
# multiplikatywnie (kolorowanie)?
# czy warto w teorię?
# Neumann-Neumann?
# Spojrzeć na https://drive.google.com/drive/u/2/folders/1x0mXSbO1OSXAdE9AR1jE-mJWURbmpuUv dobre wyniki?
# co jest dla nieciągłego współczynnika z overlapem?